FROM node:12-alpine

RUN apk update && apk add python make g++ ffmpeg
ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --production

COPY . .

CMD ["npm", "start"]