version: "3.1"

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: botato
      POSTGRES_PASSWORD: botato
      POSTGRES_DB: botato
    ports:
      - 5432:5432
  bot:
    container_name: bot
    depends_on:
      - db
    image: botato
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
