import { TextChannel, VoiceChannel, VoiceConnection } from "discord.js";
import { YouTubeSearchResults } from "youtube-search";

export interface BotSongInfo extends YouTubeSearchResults {
  requested_by?: string;
  duration?: string;
}

export interface Queue {
  textChannel: TextChannel;
  voiceChannel: VoiceChannel;
  connection: VoiceConnection;
  songs: BotSongInfo[];
  volume: number;
  playing: boolean;
  timeout?: NodeJS.Timeout;
}

// Generated by https://quicktype.io

export interface YtSearch {
  track: string;
  info:  Info;
}

export interface Info {
  identifier: string;
  isSeekable: boolean;
  author:     string;
  length:     number;
  isStream:   boolean;
  position:   number;
  title:      string;
  uri:        string;
}

