name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Execute ssh commands 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{secrets.SSH_KEY}}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
          cd /root/botato
          git fetch && git pull
          /root/.nvm/versions/node/v12.22.6/bin/npm install
          /root/.nvm/versions/node/v12.22.6/bin/npx prisma migrate deploy
          /root/.nvm/versions/node/v12.22.6/bin/npm run build
          /root/.nvm/versions/node/v12.22.6/bin/pm2 restart Botato
