name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Execute ssh commands 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{secrets.SSH_KEY}}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
          cd /root/botato
          git fetch && git pull
          source /root/.bashrc
          npm install
          npx prisma migrate deploy
          npm run build
          pm2 restart Botato
